#
# Copyright (c) 2022, Oracle and/or its affiliates. All rights reserved.
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
#
# This code is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 2 only, as
# published by the Free Software Foundation.  Oracle designates this
# particular file as subject to the "Classpath" exception as provided
# by Oracle in the LICENSE file that accompanied this code.
#
# This code is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# version 2 for more details (a copy is included in the LICENSE file that
# accompanied this code).
#
# You should have received a copy of the GNU General Public License version
# 2 along with this work; if not, write to the Free Software Foundation,
# Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
#
# Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
# or visit www.oracle.com if you need additional information or have any
# questions.
#

name: "Build (cross-compile)"

on:
  workflow_dispatch: # 启用手动触发
    inputs:
      environment: # 自定义输入参数（可选）
        description: "Deployment Environment"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - production

# 在调用方的工作流中（如 .github/workflows/main.yml）
jobs:
  build-with-gcc12:
    uses: jayduk/jdk17/.github/workflows/build-cross-compile.yml@main
    with:
      gcc-major-version: "12" # 必须传递
      extra-conf-options: "--enable-cds"
      configure-arguments: "--prefix=/usr/local"
      make-arguments: "-j4"
